services:
  # PHP-FPM service for Matomo application
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/var/www/html:rw,cached
    depends_on:
      - db

  # MariaDB database service
  db:
    image: mariadb:10.11
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - ./db.env

  # Nginx web server
  web:
    image: nginx:alpine
    volumes:
      - ../app:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  db:
